version: "3.8"

services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: