name: 参加登録
description: Web Speed Hackathon 2021 mini の参加登録フォームです
title: '[参加登録]'
labels:
  - registration
body:
  - type: markdown
    attributes:
      value: |
        # ようこそ、Web Speed Hackathon 2021 mini へ！

        - 開催期間 | **2021/12/4 (土) – 2022/1/3 (月)**
        - 参加資格 | **どなたでも自由に参加できます**

        **参加する前に、注意事項とレギュレーションを確認してください**

         - [注意事項](https://github.com/CyberAgentHack/web-speed-hackathon-2021/blob/main/README.md#注意事項)
         - [レギュレーション](https://github.com/CyberAgentHack/web-speed-hackathon-2021/blob/main/docs/REGULATION.md)
  - type: dropdown
    id: regulation
    attributes:
      label: '注意事項・レギュレーション {{regulation}}'
      options:
        - 注意事項・レギュレーションを確認して、同意しました
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 計測対象の URL

        [課題のソースコード](https://github.com/CyberAgentHack/web-speed-hackathon-2021) から、アプリケーションをデプロイして、URL を提出してください
  - type: input
    id: target-url
    attributes:
      label: '計測対象の URL {{url}}'
      placeholder: e.g.) https://web-speed-hackathon-2021.herokuapp.com/
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## アンケート項目（任意）

        :warning: **ここから先は任意回答です。このアンケート項目は一般に公開されます**
  - type: input
    id: referrer
    attributes:
      label: この Web Speed Hackathon 2021 mini をどこで知りましたか
    validations:
      required: false
  - type: input
    id: framework
    attributes:
      label: 普段利用する Web フレームワーク / ライブラリは何ですか
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 準備が整いました

        投稿すると、GitHub Actions によって自動計測が始まります！

        - :information_source: もし、10分以上何も反応がない場合は、issue を作り直してみてください
