name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@next
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: './scripts/leaderboard'
          preCommands: |
            yarn install --frozen-lockfile
            echo $SUPABASE_URL | wrangler secret put SUPABASE_URL
            echo $SUPABASE_ANON_KEY | wrangler secret put SUPABASE_ANON_KEY
            echo "$SUPABASE_URL/graphql/v1" | wrangler secret put GRAPHQL_URI
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}