name: Scoring
on:
  workflow_run:
    workflows:
      - Request
    types:
      - completed
env:
  TZ: 'Asia/Tokyo'
  WSH_SCORING_DEBUG: '${{ secrets.WSH_SCORING_DEBUG }}'
jobs:
  payload:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      result: ${{ steps.payload.outputs.result }}
    steps:
      - name: Download payload
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: .github/workflows/request.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: payload.json
          path: /tmp
      - name: Read payload
        uses: actions/github-script@v5.0.0
        id: payload
        with:
          result-encoding: json
          script: |
            const payload = require('/tmp/payload.json');
            return payload;
  vrt:
    runs-on: ubuntu-20.04
    needs:
      - payload
    outputs:
      details: ${{ steps.details.outputs.result }}
      result: ${{ steps.result.outputs.result }}
    concurrency: scoring-${{ fromJSON(needs.payload.outputs.result).id }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Run VRT
        id: vrt
        run: |
          yarn run vrt:capture --url ${{ fromJSON(needs.payload.outputs.result).url }}
          yarn run vrt:detect
      - name: Upload payload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: screenshots
          path: ./scripts/vrt/tmp/*
          retention-days: 1
      - name: Read details
        uses: actions/github-script@v5.0.0
        id: details
        with:
          result-encoding: json
          script: |
            const payload = require('./scripts/vrt/tmp/reg.json');
            return payload;
      - name: Read result
        uses: actions/github-script@v5.0.0
        id: result
        with:
          result-encoding: string
          script: |
            const payload = require('./scripts/vrt/tmp/reg.json');
            return payload.failedItems.length === 0 ? 'success' : 'failed';
  scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
    outputs:
      result: ${{ steps.scoring.outputs.export }}
    concurrency: scoring-${{ fromJSON(needs.payload.outputs.result).id }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Scoring
        id: scoring
        run: |
          yarn run scoring \
            --id ${{ fromJSON(needs.payload.outputs.result).id }} \
            --url ${{ fromJSON(needs.payload.outputs.result).url }}
        env:
          WSH_SCORING_TARGET_PATHS: '${{ secrets.WSH_SCORING_TARGET_PATHS }}'
  update:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - scoring
    if: needs.vrt.outputs.result == 'success'
    outputs:
      result: ${{ steps.update.outputs.export }}
    concurrency: update-leader-board
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: main
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Update leader board
        id: update
        run: |
          yarn run update \
            --markdown ${GITHUB_WORKSPACE}/README.md \
            --score-csv ${GITHUB_WORKSPACE}/score.csv \
            --id ${{ fromJSON(needs.payload.outputs.result).id }} \
            --url ${{ fromJSON(needs.payload.outputs.result).url }} \
            --score ${{ fromJSON(needs.scoring.outputs.result).result.score }}
      - name: Commit leader board
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
      - name: Create OGP
        run: |
          yarn run create-ogp \
            --id ${{ fromJSON(needs.payload.outputs.result).id }} \
            --score ${{ fromJSON(needs.scoring.outputs.result).result.score }} \
            --rank ${{ fromJSON(steps.update.outputs.export).rank }}
      - uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scripts/create-ogp/public
          keep_files: true
  comment-payload:
    runs-on: ubuntu-20.04
    needs:
      - payload
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            :hourglass_flowing_sand: **VRT を実行しています**

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  comment-failure-vrt:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - comment-payload
    if: always() && needs.vrt.result == 'failure'
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            :exclamation: **VRT が実行できませんでした**

            次を確認してください

            - URL が間違っていませんか
            - API `POST /api/v1/initialize` が実行できますか
            - 計測対象のページは、誰でも閲覧できるようになっていますか
            - エラーページ以外では、ステータスコードが 200 で返却されますか

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/rerun` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-vrt:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - comment-payload
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            :hourglass_flowing_sand: **Lighthouse でスコアを計測しています**

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  comment-failure-scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - scoring
      - comment-vrt
    if: always() && needs.scoring.result == 'failure'
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            :exclamation: **Lighthouse の計測ができませんでした**

            次を確認してください

            - URL が間違っていませんか
            - 計測対象のページは、誰でも閲覧できるようになっていますか
            - エラーページ以外では、ステータスコードが 200 で返却されますか

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/rerun` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-scoring:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - scoring
      - comment-vrt
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        if: needs.vrt.outputs.result == 'success'
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            スコアは **${{ fromJSON(needs.scoring.outputs.result).result.score }}** です

            :hourglass_flowing_sand: リーダーボードを更新中です...

            <details>
            <summary>buildInfo</summary>

            ```json
            ${{ toJSON(fromJSON(needs.scoring.outputs.result).buildInfo) }}
            ```

            </details>

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        if: needs.vrt.outputs.result != 'success'
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            スコアは **${{ fromJSON(needs.scoring.outputs.result).result.score }}** です

            :warning: VRT に問題があったため、リーダーボードには反映されません

            <details>
            <summary>buildInfo</summary>

            ```json
            ${{ toJSON(fromJSON(needs.scoring.outputs.result).buildInfo) }}
            ```

            </details>

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/rerun` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-failure-update:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - scoring
      - update
      - comment-scoring
    if: always() && needs.update.result == 'failure'
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーション

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            スコアは **${{ fromJSON(needs.scoring.outputs.result).result.score }}** です

            :exclamation: **リーダーボードが更新できませんでした**

            <details>
            <summary>buildInfo</summary>

            ```json
            ${{ toJSON(fromJSON(needs.scoring.outputs.result).buildInfo) }}
            ```

            </details>

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/rerun` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
  comment-update:
    runs-on: ubuntu-20.04
    needs:
      - payload
      - vrt
      - scoring
      - update
      - comment-scoring
    steps:
      - name: Create twitter share url
        uses: actions/github-script@v5.0.0
        id: share-url
        with:
          result-encoding: string
          script: |
            const text = `
            "Web Speed Hackathon 2021 mini" に挑戦しました！
            スコア ${process.env.SCORE} / 720.00 で、現在 ${process.env.RANK} 位です
            `.trim();

            const ogpUrl = new URL(`https://cyberagenthack.github.io/web-speed-hackathon-2021-leaderboard/scores/${process.env.USER_ID}/`);
            ogpUrl.searchParams.set('_', Date.now());

            const shareUrl = new URL('https://twitter.com/intent/tweet');
            shareUrl.searchParams.set('text', text);
            shareUrl.searchParams.set('url', ogpUrl);
            shareUrl.searchParams.set('hashtags', 'WebSpeedHackathon');

            return shareUrl.href;
        env:
          USER_ID: ${{ fromJSON(needs.payload.outputs.result).id }}
          SCORE: ${{ fromJSON(needs.scoring.outputs.result).result.score }}
          RANK: ${{ fromJSON(needs.update.outputs.result).rank }}
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ fromJSON(needs.payload.outputs.result).report_comment_id }}
          edit-mode: replace
          body: |
            ## レギュレーションチェック

            ${{ (needs.vrt.outputs.result == 'success' && '**差分はありませんでした**') || '**一部のページに差分があります**' }}

            <details>
            <summary>差分が見つかったページ</summary>

            :information_source: スクリーンショットは、スコア計測後に、Actions の Artifacts からダウンロードできます

            ```json
            ${{ toJSON(fromJSON(needs.vrt.outputs.details).failedItems) }}
            ```

            </details>

            ## スコア

            スコアは **${{ fromJSON(needs.scoring.outputs.result).result.score }}** です

            現在、**${{ fromJSON(needs.update.outputs.result).rank }} 位**です

            <details>
            <summary>buildInfo</summary>

            ```json
            ${{ toJSON(fromJSON(needs.scoring.outputs.result).buildInfo) }}
            ```

            </details>

            ## 結果をツイートする

            @${{ fromJSON(needs.payload.outputs.result).id }} スコアを Twitter で共有してみませんか？

            [![結果をツイートする](https://raw.githack.com/3846masa-tmp/github-actions-test/main/assets/tweet.png)](${{ steps.share-url.outputs.result }})

            ---

            Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :information_source: `/rerun` とコメントすると、もう一度計測ができます
            :information_source: 登録内容を変更する場合は、issue を閉じて作り直してください
